# Generated by Django 4.2.29 on 2026-06-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_logintoken_delete_otp_remove_telegramuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
