# Generated by Django 4.2.29 on 2026-06-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_message_edited_message_image_message_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='title_uz',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
