# Generated by Django 4.2.29 on 2026-06-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_body_en_post_body_ru_post_body_uz_post_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
